name: Release V2 OIBus version

on:
  push:
    branches:
      - oibus-v2

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: 'Tag new version'
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          signoff: "Optimistik SAS <optimistiksas@users.noreply.github.com>"
          default-branch: oibus-v2
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          prerelease: false
